from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path("dashboard", views.dashboard, name="dashboard"),
    path("bantuan", views.bantuan, name="bantuan"),
    path("users", views.users_index, name="users"),
    path("users/save", views.users_save, name="users_save"),
    path("tautan-user", views.tautan_user_index, name="tautan_user"),
    path("tautan-user/save", views.tautan_user_save, name="tautan_user_save"),
    path("tautan-user/opsi/<int:profile_id>", views.tautan_user_opsi, name="tautan_user_opsi"),
    path("users/<int:user_id>/reset-password", views.users_reset_password, name="users_reset_password"),
    path("users/<int:user_id>/toggle", views.users_toggle, name="users_toggle"),
    path("users/<int:user_id>/delete", views.users_delete, name="users_delete"),
    path("master/products", views.products_index, name="products"),
    path("master/customers", views.customers_index, name="customers"),
    path("master/suppliers", views.suppliers_index, name="suppliers"),
    path("master/sync-history", views.sync_history_index, name="sync_history"),
    path("master/sync-health", views.sync_health_index, name="sync_health"),
    path("master/kelola-pelanggan", views.pelanggan, name="kelola_pelanggan"),
    path("master/kelola-pelanggan/save", views.pelanggan_save, name="kelola_pelanggan_save"),
    path("master/kelola-supplier", views.supplier, name="kelola_supplier"),
    path("master/kelola-supplier/save", views.supplier_save, name="kelola_supplier_save"),
    # Kelola Data Referensi — sebelas entitas lewat satu key menu. Rute telanjang
    # HARUS ada: ia href menunya, dan `menu_key_for_path` mencocokkan prefix dari
    # situ sehingga `/referensi/<entitas>` dan `/save` ikut terjaga.
    path("master/referensi", views.referensi_awal, name="kelola_referensi"),
    path("master/referensi/<slug:entitas>", views.referensi, name="kelola_referensi_entitas"),
    path("master/referensi/<slug:entitas>/save", views.referensi_save,
         name="kelola_referensi_save"),
    path("master/kode-nota", views.kode_nota_index, name="kode_nota"),
    path("master/kode-nota/save", views.kode_nota_save, name="kode_nota_save"),
    # Alamat lama, dipertahankan SEMENTARA untuk masa peralihan. Halaman yang
    # sudah terbuka di tab orang lain masih memegang URL ini, dan
    # `query_string=True` menjaga `?search=` mereka ikut terbawa — tanpa itu
    # pengalihannya membuang apa yang sedang mereka cari. Boleh dihapus setelah
    # beberapa minggu; ia tak dirujuk kode mana pun (dijaga test_kelola_barang).
    path("master/update-barang", RedirectView.as_view(
        url="/admin-panel/master/update-harga", query_string=True)),
    path("master/barang-baru", RedirectView.as_view(
        url="/admin-panel/master/kelola-barang", query_string=True)),
    path("master/kelola-barang", views.barang_baru_index, name="kelola_barang"),
    path("master/kelola-barang/cari", views.barang_cari, name="kelola_barang_cari"),
    path("master/kelola-barang/muat", views.barang_muat, name="kelola_barang_muat"),
    path("master/kelola-barang/save", views.barang_baru_save, name="kelola_barang_save"),
    path("master/update-harga", views.update_barang_index, name="update_barang"),
    path("master/update-harga/harga", views.update_barang_harga, name="update_barang_harga"),
    path("master/update-harga/harga-massal", views.update_barang_harga_massal, name="update_barang_harga_massal"),
    path("master/update-harga/status", views.update_barang_status, name="update_barang_status"),
    path("master/update-harga/identitas", views.update_barang_identitas,
         name="update_barang_identitas"),
    path("master/update-harga/riwayat", views.update_barang_riwayat, name="update_barang_riwayat"),
    path("master/update-harga/detail", views.update_barang_detail, name="update_barang_detail"),
    path("master/riwayat-update-barang", views.riwayat_update_barang_index, name="riwayat_update_barang"),
    path("master/pergerakan-harga", views.pergerakan_harga_index, name="pergerakan_harga"),
    path("master/sync-harga", views.sync_harga_index, name="sync_harga"),
    path("master/sync-harga/apply", views.sync_harga_apply, name="sync_harga_apply"),
    path("master/sync-master", views.sync_master_index, name="sync_master"),
    path("master/sync-master/apply", views.sync_master_apply, name="sync_master_apply"),
    path("logs", views.logs_index, name="logs"),
    # Inventory
    path("inventory/stock", views.stock_index, name="stock"),
    path("inventory/stock/export", views.stock_export, name="stock_export"),
    path("inventory/histori", views.barang_histori_index, name="barang_histori"),
    path("inventory/stok-divisi", views.stok_divisi, name="stok_divisi"),
    path("inventory/mutasi-stok", views.mutasi_stok, name="mutasi_stok"),
    path("inventory/stok-awal", views.stok_awal_barang, name="stok_awal_barang"),
    path("inventory/transaksi", views.transaksi_barang, name="transaksi_barang"),
    path("inventory/transaksi/export", views.transaksi_barang_export, name="transaksi_barang_export"),
    path("inventory/opname", views.opname, name="opname"),
    path("inventory/opname/export", views.opname_export, name="opname_export"),
    # Koreksi stok — halaman sendiri, satu-satunya jalur tulis ke t_opname_stok.
    path("inventory/koreksi-stok", views.koreksi_stok_index, name="koreksi_stok"),
    path("inventory/koreksi-stok/save", views.koreksi_stok_save, name="koreksi_stok_save"),
    path("inventory/koreksi-stok/cari", views.koreksi_stok_cari, name="koreksi_stok_cari"),
    # Laporan penjualan / pembelian
    path("laporan/penjualan", views.penjualan_all, name="penjualan_all"),
    path("laporan/penjualan/export", views.penjualan_all_export, name="penjualan_all_export"),
    path("laporan/penjualan-hpp", views.penjualan_hpp, name="penjualan_hpp"),
    path("laporan/penjualan-hpp/export", views.penjualan_hpp_export, name="penjualan_hpp_export"),
    path("laporan/penjualan-nota", views.penjualan_nota, name="penjualan_nota"),
    path("laporan/penjualan-nota/export", views.penjualan_nota_export, name="penjualan_nota_export"),
    path("laporan/penjualan-customer", views.penjualan_customer, name="penjualan_customer"),
    path("laporan/penjualan-customer/export", views.penjualan_customer_export, name="penjualan_customer_export"),
    path("laporan/penjualan-user", views.penjualan_user, name="penjualan_user"),
    path("laporan/penjualan-user/export", views.penjualan_user_export, name="penjualan_user_export"),
    path("laporan/penjualan-periode", views.penjualan_periode, name="penjualan_periode"),
    path("laporan/penjualan-periode/export", views.penjualan_periode_export, name="penjualan_periode_export"),
    path("laporan/retur-penjualan", views.retur_penjualan, name="retur_penjualan"),
    path("laporan/retur-penjualan/export", views.retur_penjualan_export, name="retur_penjualan_export"),
    path("laporan/piutang", views.piutang, name="piutang"),
    path("laporan/piutang/export", views.piutang_export, name="piutang_export"),
    path("laporan/pembelian", views.pembelian, name="pembelian"),
    path("laporan/pembelian/export", views.pembelian_export, name="pembelian_export"),
    path("laporan/pembelian-supplier", views.pembelian_supplier, name="pembelian_supplier"),
    path("laporan/pembelian-supplier/export", views.pembelian_supplier_export, name="pembelian_supplier_export"),
    path("laporan/pembelian-periode", views.pembelian_periode, name="pembelian_periode"),
    path("laporan/pembelian-periode/export", views.pembelian_periode_export, name="pembelian_periode_export"),
    path("laporan/retur-pembelian", views.retur_pembelian, name="retur_pembelian"),
    path("laporan/retur-pembelian/export", views.retur_pembelian_export, name="retur_pembelian_export"),
    # Analitik (FMI)
    path("analitik/fmi-penjualan", views.fmi_penjualan, name="fmi_penjualan"),
    path("analitik/fmi-penjualan/export", views.fmi_penjualan_export, name="fmi_penjualan_export"),
    path("analitik/fmi-stok", views.fmi_stok, name="fmi_stok"),
    path("analitik/fmi-stok/export", views.fmi_stok_export, name="fmi_stok_export"),
    path("analitik/klasifikasi-pelanggan", views.klasifikasi_pelanggan, name="klasifikasi_pelanggan"),
    path("analitik/klasifikasi-pelanggan/export", views.klasifikasi_pelanggan_export,
         name="klasifikasi_pelanggan_export"),
    path("analitik/klasifikasi-pelanggan/detail", views.klasifikasi_pelanggan_detail,
         name="klasifikasi_pelanggan_detail"),
    # Promo & Voucher
    path("promo/diskon", views.promo, name="promo"),
    path("promo/diskon/export", views.promo_export, name="promo_export"),
    path("promo/voucher", views.voucher, name="voucher"),
    path("promo/voucher/export", views.voucher_export, name="voucher_export"),
    # Kas & Shift
    path("kas/harian", views.kas_harian, name="kas"),
    path("kas/harian/export", views.kas_harian_export, name="kas_harian_export"),
    path("kas/shift", views.shift, name="shift"),
    path("kas/shift/export", views.shift_export, name="shift_export"),
    # Jalur TULIS kas. Href menunya `/kas/input/<jenis>`, jadi tiap jenis punya
    # key menunya sendiri dan `/save` ikut terjaga lewat pencocokan prefix.
    path("kas/input/<slug:jenis>", views.kas_input_index, name="kas_input"),
    path("kas/input/<slug:jenis>/save", views.kas_input_save, name="kas_input_save"),
    path("laporan/biaya-operasional", views.biaya_operasional, name="biaya_operasional"),
    path("laporan/biaya-operasional/export", views.biaya_operasional_export, name="biaya_operasional_export"),
    path("laporan/biaya-kategori", views.biaya_kategori, name="biaya_kategori"),
    path("laporan/biaya-kategori/export", views.biaya_kategori_export, name="biaya_kategori_export"),
    # Menu management (superadmin) + own profile
    path("menus", views.menus_index, name="menus"),
    path("menus/save", views.menus_save, name="menus_save"),
    path("profile", views.profile_view, name="profile"),
    path("profile/save", views.profile_save, name="profile_save"),
]
