# Generated by Django 5.2.16 on 2026-09-07 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bahan',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('awalan_nota', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'db_table': 'divisi',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kategori',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Merek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'merek',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'model_barang',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'satuan',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'warna',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.CharField(blank=True, max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('bahan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.bahan')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.kategori')),
                ('merek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.merek')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.modelbarang')),
                ('satuan_dasar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barang_dasar', to='bisnis.satuan')),
                ('warna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.warna')),
            ],
            options={
                'db_table': 'barang',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('tanggal', models.DateField()),
                ('pelanggan_id', models.BigIntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diskon', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pajak', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('batal', 'Batal')], default='aktif', max_length=10)),
                ('dibuat_oleh', models.IntegerField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
            ],
            options={
                'db_table': 'penjualan',
            },
        ),
        migrations.CreateModel(
            name='PergerakanStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('masuk', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('keluar', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jenis', models.CharField(choices=[('saldo_awal', 'Saldo Awal'), ('penjualan', 'Penjualan'), ('retur_jual', 'Retur Penjualan'), ('pembelian', 'Pembelian'), ('retur_beli', 'Retur Pembelian'), ('mutasi_masuk', 'Mutasi Masuk'), ('mutasi_keluar', 'Mutasi Keluar'), ('koreksi', 'Koreksi Stok')], max_length=20)),
                ('sumber_tipe', models.CharField(blank=True, max_length=20)),
                ('sumber_id', models.BigIntegerField(blank=True, null=True)),
                ('no_rujukan', models.CharField(blank=True, max_length=30)),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.barang')),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.satuan')),
            ],
            options={
                'db_table': 'pergerakan_stok',
            },
        ),
        migrations.CreateModel(
            name='PenjualanBaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diskon', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.barang')),
                ('penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baris', to='bisnis.penjualan')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.satuan')),
            ],
            options={
                'db_table': 'penjualan_baris',
            },
        ),
        migrations.CreateModel(
            name='BarangSatuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satuan', to='bisnis.barang')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.satuan')),
            ],
            options={
                'db_table': 'barang_satuan',
            },
        ),
        migrations.AddIndex(
            model_name='penjualan',
            index=models.Index(fields=['tanggal'], name='ix_jual_tgl'),
        ),
        migrations.AddIndex(
            model_name='penjualan',
            index=models.Index(fields=['divisi', 'tanggal'], name='ix_jual_divisi_tgl'),
        ),
        migrations.AddIndex(
            model_name='penjualan',
            index=models.Index(fields=['pelanggan_id', 'tanggal'], name='ix_jual_pelanggan_tgl'),
        ),
        migrations.AddIndex(
            model_name='pergerakanstok',
            index=models.Index(fields=['barang', 'divisi', 'tanggal'], name='ix_gerak_barang_divisi_tgl'),
        ),
        migrations.AddIndex(
            model_name='pergerakanstok',
            index=models.Index(fields=['divisi', 'tanggal'], name='ix_gerak_divisi_tgl'),
        ),
        migrations.AddIndex(
            model_name='pergerakanstok',
            index=models.Index(fields=['sumber_tipe', 'sumber_id'], name='ix_gerak_sumber'),
        ),
        migrations.AddConstraint(
            model_name='pergerakanstok',
            constraint=models.CheckConstraint(condition=models.Q(('masuk', 0), ('keluar', 0), _connector='OR'), name='ck_gerak_satu_arah'),
        ),
        migrations.AddConstraint(
            model_name='pergerakanstok',
            constraint=models.CheckConstraint(condition=models.Q(('masuk__gte', 0), ('keluar__gte', 0)), name='ck_gerak_tak_negatif'),
        ),
        migrations.AddIndex(
            model_name='penjualanbaris',
            index=models.Index(fields=['barang'], name='ix_jual_baris_barang'),
        ),
        migrations.AddConstraint(
            model_name='barangsatuan',
            constraint=models.UniqueConstraint(fields=('barang', 'satuan'), name='uq_barang_satuan'),
        ),
        migrations.AddConstraint(
            model_name='barangsatuan',
            constraint=models.CheckConstraint(condition=models.Q(('isi__gt', 0)), name='ck_barang_satuan_isi_positif'),
        ),
    ]
