# Generated by Django 5.2.16 on 2026-09-07 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('keterangan', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'bank',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KategoriBiaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('keterangan', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'kategori_biaya',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('kode_telepon', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'db_table': 'kota',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Negara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'negara',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'voucher',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('no_rekening', models.CharField(blank=True, max_length=30)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('kontak', models.CharField(blank=True, max_length=50)),
                ('saldo_awal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=50)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.bank')),
                ('kota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.kota')),
            ],
            options={
                'db_table': 'kas',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kota',
            name='negara',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.negara'),
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(blank=True, max_length=200)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('hp', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('kontak', models.CharField(blank=True, max_length=50)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('aktif', models.BooleanField(default=True)),
                ('batas_piutang', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diskon_persen', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('kota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.kota')),
            ],
            options={
                'db_table': 'pelanggan',
                'ordering': ['nama'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(blank=True, max_length=200)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('hp', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('kontak', models.CharField(blank=True, max_length=50)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('aktif', models.BooleanField(default=True)),
                ('rekening', models.CharField(blank=True, max_length=30)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.bank')),
                ('kota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.kota')),
            ],
            options={
                'db_table': 'pemasok',
                'ordering': ['nama'],
                'abstract': False,
            },
        ),
    ]
