# Generated by Django 5.2.16 on 2026-09-11 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0002_bank_kategoribiaya_kota_negara_voucher_kas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.voucher'),
        ),
    ]
