# Generated by Django 5.2.16 on 2026-09-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0003_penjualan_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='jenis_bayar',
            field=models.CharField(choices=[('kredit', 'Kredit'), ('tunai', 'Tunai'), ('lunas', 'Lunas')], default='tunai', max_length=10),
        ),
    ]
