# Generated by Django 5.2.16 on 2026-09-11 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0004_penjualan_jenis_bayar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('tanggal', models.DateField()),
                ('pemasok_id', models.BigIntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diskon', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pajak', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jenis_bayar', models.CharField(choices=[('kredit', 'Kredit'), ('tunai', 'Tunai'), ('lunas', 'Lunas')], default='tunai', max_length=10)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('batal', 'Batal')], default='aktif', max_length=10)),
                ('dibuat_oleh', models.IntegerField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
            ],
            options={
                'db_table': 'pembelian',
            },
        ),
        migrations.CreateModel(
            name='PembelianBaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diskon', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.barang')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baris', to='bisnis.pembelian')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.satuan')),
            ],
            options={
                'db_table': 'pembelian_baris',
            },
        ),
        migrations.AddIndex(
            model_name='pembelian',
            index=models.Index(fields=['tanggal'], name='ix_beli_tgl'),
        ),
        migrations.AddIndex(
            model_name='pembelian',
            index=models.Index(fields=['divisi', 'tanggal'], name='ix_beli_divisi_tgl'),
        ),
        migrations.AddIndex(
            model_name='pembelian',
            index=models.Index(fields=['pemasok_id', 'tanggal'], name='ix_beli_pemasok_tgl'),
        ),
        migrations.AddIndex(
            model_name='pembelianbaris',
            index=models.Index(fields=['barang'], name='ix_beli_baris_barang'),
        ),
    ]
