# Generated by Django 5.2.16 on 2026-09-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0005_pembelian_pembelianbaris_pembelian_ix_beli_tgl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoribiaya',
            name='jenis',
            field=models.CharField(choices=[('penjualan', 'Operasional (Penjualan)'), ('adm_umum', 'Operasional (Adm. dan Umum)'), ('produksi_langsung', 'Produksi (Biaya Langsung)'), ('produksi_tak_langsung', 'Produksi (Biaya Tak Langsung)')], default='adm_umum', max_length=24),
        ),
    ]
