# Generated by Django 5.2.16 on 2026-09-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0006_kategoribiaya_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalKas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('tanggal', models.DateField()),
                ('jenis', models.CharField(choices=[('biaya', 'Biaya'), ('pendapatan', 'Pendapatan'), ('penambahan', 'Penambahan Kas'), ('mutasi', 'Mutasi Antar-Kas')], max_length=12)),
                ('jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('dibuat_oleh', models.IntegerField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('divisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
                ('kas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurnal', to='bisnis.kas')),
                ('kas_tujuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_masuk', to='bisnis.kas')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.kategoribiaya')),
            ],
            options={
                'db_table': 'jurnal_kas',
                'indexes': [models.Index(fields=['tanggal'], name='ix_jurkas_tgl'), models.Index(fields=['kas', 'tanggal'], name='ix_jurkas_kas_tgl'), models.Index(fields=['jenis', 'tanggal'], name='ix_jurkas_jenis_tgl')],
            },
        ),
    ]
