# Generated by Django 5.2.16 on 2026-09-11 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0007_jurnalkas'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='kas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penjualan', to='bisnis.kas'),
        ),
    ]
