# Generated by Django 5.2.16 on 2026-09-12 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0008_penjualan_kas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pegawai',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pengguna',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='penjualanbaris',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.pegawai'),
        ),
    ]
