# Generated by Django 5.2.16 on 2026-09-12 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0009_pegawai_pengguna_penjualanbaris_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='pengguna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penjualan', to='bisnis.pengguna'),
        ),
    ]
