# Generated by Django 5.2.16 on 2026-09-12 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0010_penjualan_pengguna'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoreksiStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('tanggal', models.DateTimeField()),
                ('jenis', models.CharField(choices=[('hilang', 'Hilang'), ('rusak', 'Rusak'), ('lain_plus', 'Lain-Lain (+)'), ('lain_minus', 'Lain-Lain (−)')], max_length=12)),
                ('keterangan', models.CharField(blank=True, max_length=100)),
                ('dibuat_oleh', models.IntegerField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.pengguna')),
            ],
            options={
                'db_table': 'koreksi_stok',
            },
        ),
        migrations.CreateModel(
            name='KoreksiStokBaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.barang')),
                ('koreksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baris', to='bisnis.koreksistok')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.satuan')),
            ],
            options={
                'db_table': 'koreksi_stok_baris',
            },
        ),
        migrations.AddIndex(
            model_name='koreksistok',
            index=models.Index(fields=['tanggal'], name='ix_koreksi_tgl'),
        ),
        migrations.AddIndex(
            model_name='koreksistokbaris',
            index=models.Index(fields=['barang'], name='ix_koreksi_baris_barang'),
        ),
    ]
