# Generated by Django 5.2.16 on 2026-09-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0011_koreksistok_koreksistokbaris_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenjualanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('tanggal', models.DateTimeField()),
                ('tanggal_terima', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('terbuka', 'Terbuka'), ('jadi_nota', 'Jadi Nota')], default='terbuka', max_length=10)),
                ('nomor_nota', models.CharField(blank=True, max_length=30, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dibuat_oleh', models.IntegerField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
                ('pelanggan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.pelanggan')),
            ],
            options={
                'db_table': 'penjualan_order',
            },
        ),
        migrations.CreateModel(
            name='PenjualanOrderBaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.barang')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baris', to='bisnis.penjualanorder')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.satuan')),
            ],
            options={
                'db_table': 'penjualan_order_baris',
            },
        ),
        migrations.AddIndex(
            model_name='penjualanorder',
            index=models.Index(fields=['tanggal'], name='ix_order_jual_tgl'),
        ),
        migrations.AddIndex(
            model_name='penjualanorderbaris',
            index=models.Index(fields=['barang'], name='ix_order_jual_baris_brg'),
        ),
    ]
