# Generated by Django 5.2.16 on 2026-09-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0012_penjualanorder_penjualanorderbaris_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaraBayar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cara_bayar',
                'ordering': ['kode'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='divisi',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PembelianRetur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('tanggal', models.DateTimeField()),
                ('no_bukti', models.CharField(blank=True, max_length=30)),
                ('keterangan', models.CharField(blank=True, max_length=100)),
                ('dibuat_oleh', models.IntegerField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('cara_bayar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.carabayar')),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
                ('kas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.kas')),
                ('pemasok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.pemasok')),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.pengguna')),
            ],
            options={
                'db_table': 'pembelian_retur',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PembelianReturBaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.barang')),
                ('retur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baris', to='bisnis.pembelianretur')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.satuan')),
            ],
            options={
                'db_table': 'pembelian_retur_baris',
            },
        ),
        migrations.CreateModel(
            name='PenjualanRetur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=30, unique=True)),
                ('tanggal', models.DateTimeField()),
                ('no_bukti', models.CharField(blank=True, max_length=30)),
                ('keterangan', models.CharField(blank=True, max_length=100)),
                ('dibuat_oleh', models.IntegerField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('cara_bayar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.carabayar')),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
                ('kas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.kas')),
                ('pelanggan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.pelanggan')),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.pengguna')),
            ],
            options={
                'db_table': 'penjualan_retur',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenjualanReturBaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.barang')),
                ('retur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baris', to='bisnis.penjualanretur')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bisnis.pegawai')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.satuan')),
            ],
            options={
                'db_table': 'penjualan_retur_baris',
            },
        ),
        migrations.AddIndex(
            model_name='pembelianretur',
            index=models.Index(fields=['tanggal'], name='ix_retur_beli_tgl'),
        ),
        migrations.AddIndex(
            model_name='pembelianreturbaris',
            index=models.Index(fields=['barang'], name='ix_retur_beli_baris_brg'),
        ),
        migrations.AddIndex(
            model_name='penjualanretur',
            index=models.Index(fields=['tanggal'], name='ix_retur_jual_tgl'),
        ),
        migrations.AddIndex(
            model_name='penjualanreturbaris',
            index=models.Index(fields=['barang'], name='ix_retur_jual_baris_brg'),
        ),
    ]
