# Generated by Django 5.2.16 on 2026-09-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0013_carabayar_divisi_keterangan_pembelianretur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='diskon_persen',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='jatuh_tempo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='penjualanbaris',
            name='diskon_persen',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
