# Generated by Django 5.2.16 on 2026-09-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0014_penjualan_diskon_persen_penjualan_jatuh_tempo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='diskon_persen',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='nomor_order',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='pajak_persen',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='ppnbm_persen',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='pembelianbaris',
            name='diskon_persen',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
