# Generated by Django 5.2.16 on 2026-09-12 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0015_pembelian_diskon_persen_pembelian_keterangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan',
            name='pajak_persen',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='BarangDivisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_awal', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('harga_beli_awal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('stok_min', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_divisi', to='bisnis.barang')),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bisnis.divisi')),
            ],
            options={
                'db_table': 'barang_divisi',
                'constraints': [models.UniqueConstraint(fields=('barang', 'divisi'), name='uq_barang_divisi')],
            },
        ),
    ]
