# Generated by Django 5.2.16 on 2026-09-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0016_penjualan_pajak_persen_barangdivisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='pabrik',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='ukuran',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
