# Generated by Django 5.2.16 on 2026-09-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0017_barang_pabrik_barang_ukuran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembelian',
            name='diskon_persen',
        ),
        migrations.RemoveField(
            model_name='pembelianbaris',
            name='diskon_persen',
        ),
        migrations.RemoveField(
            model_name='penjualan',
            name='diskon_persen',
        ),
        migrations.RemoveField(
            model_name='penjualanbaris',
            name='diskon_persen',
        ),
        migrations.AddField(
            model_name='pembelian',
            name='diskon_ghb',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pembelianbaris',
            name='diskon_ghb',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='diskon_ghb',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='penjualanbaris',
            name='diskon_ghb',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
