# Generated by Django 5.2.16 on 2026-09-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0018_remove_pembelian_diskon_persen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalkas',
            name='tanggal',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pembelian',
            name='tanggal',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='penjualan',
            name='tanggal',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pergerakanstok',
            name='tanggal',
            field=models.DateTimeField(),
        ),
    ]
