# Generated by Django 5.2.17 on 2026-09-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0019_alter_jurnalkas_tanggal_alter_pembelian_tanggal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalkas',
            name='tanggal_server',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='koreksistok',
            name='tanggal_server',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pembelian',
            name='tanggal_server',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pembelianretur',
            name='tanggal_server',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penjualan',
            name='tanggal_server',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penjualanorder',
            name='tanggal_server',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penjualanretur',
            name='tanggal_server',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
