# Generated by Django 5.2.17 on 2026-09-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisnis', '0020_jurnalkas_tanggal_server_koreksistok_tanggal_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembelian',
            name='jatuh_tempo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
