# Generated by Django 5.2.15 on 2026-07-05 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_serverprofile_cost_source'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('feature', models.CharField(max_length=30)),
                ('mode', models.CharField(blank=True, max_length=30)),
                ('src_name', models.CharField(blank=True, max_length=100)),
                ('dst_name', models.CharField(blank=True, max_length=100)),
                ('compared_count', models.PositiveIntegerField(default=0)),
                ('applied_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Berhasil'), ('partial', 'Sebagian'), ('failed', 'Gagal')], default='ok', max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dst_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs_dst', to='connections.serverprofile')),
                ('src_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs_src', to='connections.serverprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
