# Generated by Django 5.2.15 on 2026-07-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0003_serverprofile_report_source"),
        ("core", "0002_synclog"),
    ]

    operations = [
        migrations.CreateModel(
            name="CdcSyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=64)),
                ("last_lsn", models.CharField(blank=True, max_length=20)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_rows_applied", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="ok", max_length=10)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cdc_cursors",
                        to="connections.serverprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "table_name"),
                        name="unique_cdc_cursor_per_table",
                    )
                ],
            },
        ),
    ]
