# Generated by Django 5.2.15 on 2026-07-11 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_serverprofile_report_source'),
        ('core', '0003_cdcsynccursor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('profile_name', models.CharField(blank=True, max_length=100)),
                ('kd_barang', models.CharField(max_length=30)),
                ('nama_barang', models.CharField(blank=True, max_length=150)),
                ('field', models.CharField(choices=[('harga', 'Harga Jual'), ('status_barang', 'Status Barang'), ('status_divisi', 'Status Divisi'), ('status_satuan', 'Status Satuan')], max_length=20)),
                ('kd_ref', models.CharField(blank=True, max_length=30)),
                ('nilai_lama', models.CharField(blank=True, max_length=100)),
                ('nilai_baru', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barang_update_logs', to='connections.serverprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barang_update_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'kd_barang', '-created_at'], name='core_barang_profile_ef0016_idx')],
            },
        ),
    ]
