# Generated by Django 5.2.15 on 2026-07-11 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_serverprofile_report_source'),
        ('core', '0004_barangupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangHargaChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=100)),
                ('kd_barang', models.CharField(max_length=30)),
                ('nama_barang', models.CharField(blank=True, max_length=150)),
                ('kd_satuan', models.CharField(max_length=30)),
                ('harga_lama', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('harga_baru', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harga_changes', to='connections.serverprofile')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['profile', '-detected_at'], name='core_barang_profile_c14b0c_idx'), models.Index(fields=['kd_barang', '-detected_at'], name='core_barang_kd_bara_7f7bc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BarangHargaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_barang', models.CharField(max_length=30)),
                ('kd_satuan', models.CharField(max_length=30)),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harga_states', to='connections.serverprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'kd_barang', 'kd_satuan'], name='core_barang_profile_e7f48f_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'kd_barang', 'kd_satuan'), name='unique_harga_state_sku')],
            },
        ),
    ]
