# Generated by Django 5.2.16 on 2026-07-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_stoksnapshotbaserun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangupdatelog',
            name='field',
            field=models.CharField(choices=[('harga', 'Harga Jual'), ('status_barang', 'Status Barang'), ('status_divisi', 'Status Divisi'), ('status_satuan', 'Status Satuan'), ('nama', 'Nama Barang'), ('keterangan', 'Keterangan')], max_length=20),
        ),
    ]
