# Generated by Django 5.2.16 on 2026-08-01 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_serverprofile_report_source'),
        ('core', '0009_alter_barangupdatelog_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.BigIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_rows_applied', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('source_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_cursors_out', to='connections.serverprofile')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_cursors_in', to='connections.serverprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_profile', 'target_profile'), name='unique_feed_cursor_per_pair')],
            },
        ),
        migrations.CreateModel(
            name='SyncDeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.BigIntegerField(default=0)),
                ('table_aksi', models.CharField(blank=True, max_length=255)),
                ('formatted_data', models.TextField(blank=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letters_out', to='connections.serverprofile')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letters_in', to='connections.serverprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_profile', '-created_at'], name='core_syncde_source__52a794_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncHealthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=100)),
                ('antre', models.BigIntegerField(default=0)),
                ('antre_tertua', models.DateTimeField(blank=True, null=True)),
                ('antre_terbaru', models.DateTimeField(blank=True, null=True)),
                ('watermark_get', models.DateTimeField(blank=True, null=True)),
                ('feed_id', models.BigIntegerField(blank=True, null=True)),
                ('feed_waktu', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'Sehat'), ('lambat', 'Lambat'), ('mati', 'Mati'), ('offline', 'Tak terhubung')], default='ok', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_health_samples', to='connections.serverprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='core_synche_profile_57f80c_idx')],
            },
        ),
    ]
