# Generated by Django 5.2.16 on 2026-08-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_serverprofile_kode_sumber_and_more'),
        ('core', '0010_feedsynccursor_syncdeadletter_synchealthsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubPullState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutup_buku', models.DateTimeField(blank=True, null=True)),
                ('arsip_selesai_at', models.DateTimeField(blank=True, null=True)),
                ('cocok_terakhir_at', models.DateTimeField(blank=True, null=True)),
                ('segar_terakhir_at', models.DateTimeField(blank=True, null=True)),
                ('hari_beda', models.IntegerField(default=0)),
                ('rows_header', models.BigIntegerField(default=0)),
                ('rows_detail', models.BigIntegerField(default=0)),
                ('rows_deleted', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('source_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_pull_out', to='connections.serverprofile')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_pull_in', to='connections.serverprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_profile', 'target_profile'), name='unique_hub_pull_per_pair')],
            },
        ),
    ]
