# Generated by Django 5.2.16 on 2026-08-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hubpullstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubpullstate',
            name='arsip_sampai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
