# Generated by Django 5.2.16 on 2026-09-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_serverprofile_kode_sumber_and_more'),
        ('core', '0012_hubpullstate_arsip_sampai'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPerusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perusahaan', models.CharField(blank=True, default='', max_length=200)),
                ('alamat', models.CharField(blank=True, default='', max_length=300)),
                ('kota', models.CharField(blank=True, default='', max_length=100)),
                ('telp', models.CharField(blank=True, default='', max_length=60)),
                ('hp', models.CharField(blank=True, default='', max_length=60)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('website', models.CharField(blank=True, default='', max_length=120)),
                ('nama_kontak', models.CharField(blank=True, default='', max_length=120)),
                ('diperbarui_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_perusahaan', to='connections.serverprofile')),
            ],
        ),
    ]
