# Generated by Django 5.2.16 on 2026-09-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_tandai_profil_uji'),
        ('core', '0013_infoperusahaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferArunika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('sumber_nama', models.CharField(blank=True, max_length=100)),
                ('dari', models.DateField()),
                ('sampai', models.DateField()),
                ('tutup_buku', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('berjalan', 'Berjalan'), ('selesai', 'Selesai'), ('gagal', 'Gagal'), ('terputus', 'Terputus')], default='berjalan', max_length=10)),
                ('tahap', models.CharField(blank=True, max_length=100)),
                ('langkah', models.JSONField(blank=True, default=list)),
                ('pesan_galat', models.TextField(blank=True)),
                ('total_baris', models.PositiveIntegerField(default=0)),
                ('total_dilewati', models.PositiveIntegerField(default=0)),
                ('dibuat_oleh', models.CharField(blank=True, max_length=150)),
                ('mulai_pada', models.DateTimeField(auto_now_add=True)),
                ('selesai_pada', models.DateTimeField(blank=True, null=True)),
                ('profil_arunika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_arunika_tujuan', to='connections.serverprofile')),
                ('profil_legacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_arunika_legacy', to='connections.serverprofile')),
                ('sumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_arunika_sumber', to='connections.serverprofile')),
            ],
            options={
                'ordering': ['-mulai_pada'],
            },
        ),
    ]
