# Generated by Django 5.2.17 on 2026-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transferarunika'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('ok', 'Berhasil'), ('partial', 'Sebagian'), ('failed', 'Gagal'), ('berjalan', 'Berjalan')], default='ok', max_length=10),
        ),
    ]
