# Generated by Django 5.2.17 on 2026-09-16 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_tandai_profil_uji'),
        ('core', '0015_synclog_duration_ms_alter_synclog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadanganBerkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('pangkal', 'Basis data pangkal'), ('amphoreus', 'Pusat AMPHOREUS')], max_length=10)),
                ('nama_berkas', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('ukuran_byte', models.BigIntegerField(default=0)),
                ('dibuat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dibuat_oleh', models.CharField(blank=True, max_length=150)),
                ('verifikasi_at', models.DateTimeField(blank=True, null=True)),
                ('verifikasi_ok', models.BooleanField(null=True)),
                ('verifikasi_pesan', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadangan', to='connections.serverprofile')),
            ],
            options={
                'ordering': ['-dibuat_at'],
                'constraints': [models.UniqueConstraint(fields=('jenis', 'path'), name='unique_cadangan_path')],
            },
        ),
    ]
