# Generated by Django 5.2.17 on 2026-09-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_tandai_profil_uji'),
        ('core', '0016_cadanganberkas'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hargasnapshotrun',
            name='unique_harga_snapshot_run_per_day',
        ),
        migrations.RemoveConstraint(
            model_name='stoksnapshotbaserun',
            name='unique_stok_snapshot_base_per_month',
        ),
        migrations.RemoveConstraint(
            model_name='stoksnapshotrun',
            name='unique_stok_snapshot_run_per_day',
        ),
        migrations.AddConstraint(
            model_name='hargasnapshotrun',
            constraint=models.UniqueConstraint(condition=models.Q(('profile__isnull', False)), fields=('profile', 'run_date'), name='unique_harga_snapshot_run_per_day'),
        ),
        migrations.AddConstraint(
            model_name='stoksnapshotbaserun',
            constraint=models.UniqueConstraint(condition=models.Q(('profile__isnull', False)), fields=('profile', 'base_month'), name='unique_stok_snapshot_base_per_month'),
        ),
        migrations.AddConstraint(
            model_name='stoksnapshotrun',
            constraint=models.UniqueConstraint(condition=models.Q(('profile__isnull', False)), fields=('profile', 'run_date'), name='unique_stok_snapshot_run_per_day'),
        ),
    ]
