# Generated by Django 5.2.17 on 2026-09-21 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_tandai_profil_uji'),
        ('core', '0017_snapshot_unik_hanya_dengan_profil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BayarNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(max_length=30)),
                ('dibayar', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bayar_nota', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bayar_nota', to='connections.serverprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'no_transaksi'), name='unique_bayar_nota')],
            },
        ),
    ]
