# Generated by Django 5.2.17 on 2026-09-25 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def buat_kepala_rantai(apps, schema_editor):
    """Satu baris kepala rantai hash, supaya penulis pertama tak perlu
    membuatnya sendiri di tengah permintaan (lihat `models._kunci_rantai`)."""
    RantaiJejak = apps.get_model("core", "RantaiJejak")
    RantaiJejak.objects.using(schema_editor.connection.alias).get_or_create(kunci="utama")


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0008_lingkungan_internal"),
        ("core", "0018_bayarnota"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RantaiJejak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kunci",
                    models.CharField(default="utama", max_length=10, unique=True),
                ),
                ("hash_terakhir", models.CharField(blank=True, max_length=64)),
                ("id_terakhir", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="activitylog",
            name="alasan",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="hash_prev",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="jenis_dokumen",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="no_dokumen",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="connections.serverprofile",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="profile_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["no_dokumen", "profile_name"], name="ix_log_dokumen"
            ),
        ),
        migrations.RunPython(buat_kepala_rantai, migrations.RunPython.noop),
    ]
