# Generated by Django 5.2.15 on 2026-06-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(choices=[('gudang', 'Gudang'), ('grosir', 'Grosir'), ('retail', 'Retail')], default='grosir', max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=1433)),
                ('db_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password_encrypted', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_status', models.CharField(choices=[('unknown', 'Belum dites'), ('online', 'Online'), ('offline', 'Offline')], default='unknown', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['db_type', 'name'],
            },
        ),
    ]
