# Generated by Django 5.2.15 on 2026-07-01 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprofile',
            name='cost_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_children', to='connections.serverprofile'),
        ),
    ]
