# Generated by Django 5.2.15 on 2026-07-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_serverprofile_cost_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverprofile",
            name="report_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_children",
                to="connections.serverprofile",
            ),
        ),
    ]
