# Generated by Django 5.2.16 on 2026-08-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_serverprofile_report_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprofile',
            name='kode_sumber',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='serverprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('kode_sumber__gt', '')), fields=('kode_sumber',), name='unique_kode_sumber_terisi'),
        ),
    ]
