# Generated by Django 5.2.16 on 2026-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_serverprofile_kode_sumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprofile',
            name='db_arunika',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
