# Generated by Django 5.2.16 on 2026-09-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_serverprofile_db_arunika'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverprofile',
            name='lingkungan',
            field=models.CharField(choices=[('produksi', 'Produksi'), ('uji', 'Uji coba')], default='produksi', max_length=10),
        ),
    ]
