# Generated by Django 5.2.16 on 2026-07-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hidden_data_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
