# Generated by Django 5.2.16 on 2026-08-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_hidden_data_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kd_divisi',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='kd_user',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
