# Generated by Django 5.2.16 on 2026-08-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_kd_divisi_user_kd_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kd_pegawai',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
