# Generated by Django 5.2.16 on 2026-08-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_kd_pegawai'),
        ('connections', '0004_serverprofile_kode_sumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='server_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengguna', to='connections.serverprofile'),
        ),
    ]
