# Generated by Django 5.2.16 on 2026-08-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_tautan_user_per_koneksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_dibaca_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
